drop table if exists produse;
CREATE TABLE Produse (
    NR_CRT INT PRIMARY KEY AUTO_INCREMENT,
    PRODUS VARCHAR(30) NOT NULL,
    PRET_BUC INT NOT NULL,
    BUCATI INT NOT NULL,
    PRET_TOTAL INT NOT NULL DEFAULT 0
);